/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [IInventoryId]
       [IDeviceLocation]
      ,[IDeviceName]
	  ,[IIPAddress]
      ,[IComment]
      ,[IScanInterval]
      ,[IScanTimerIsActive]
      ,[IIsActive]
      ,[IIsDeleted]
      ,[IRecordDateTime]
      ,[ISStatus]
      ,[SSOidName]
      ,[SSOid]
      ,[DTType]
      ,[DMModel]
      ,[DVVendor]
      ,[CRAgreementCompanyName]
      ,[CRAgreementStart]
      ,[CRAgreementStop]
      ,[CuType]
      ,[CRAgreementColorPrice]
      ,[CRAgreementBWPrice]
      ,[CRComment]
      ,[CRIsActive]
      ,[CRIsDeleted]
      ,[CRRecordDateTime]
  FROM [PrinterCounterCollector].[dbo].[V_Inventory]
  --WHERE IInventoryId = 1 AND IDeviceTypeId = 1 AND IDeviceModelId = 1 AND IDeviceVendorId = 1

